import type { Metadata } from "next";
import { Libre_Baskerville } from "next/font/google"
import { Provider } from "@/components/ui/provider"
import { WordStoreProvider } from "@/providers/WordStoreProvider";

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Nextionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={libreBaskerville.variable} suppressHydrationWarning>
      <body>
        <Provider>
          <WordStoreProvider>
            {children}
          </WordStoreProvider>
        </Provider>
      </body>
    </html>
  );
}
